module.exports = {
  apps: [
    // Backend Instance 1
    {
      name: 'backend-3001',
      script: './backend/dist/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        INSTANCE_ID: 'backend-1',
      },
      error_file: './logs/backend-3001-error.log',
      out_file: './logs/backend-3001-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: false,
      autorestart: true,
      max_memory_restart: '512M',
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
    // Backend Instance 2
    {
      name: 'backend-3002',
      script: './backend/dist/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
        INSTANCE_ID: 'backend-2',
      },
      error_file: './logs/backend-3002-error.log',
      out_file: './logs/backend-3002-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: false,
      autorestart: true,
      max_memory_restart: '512M',
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
    // Backend Instance 3
    {
      name: 'backend-3003',
      script: './backend/dist/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
        INSTANCE_ID: 'backend-3',
      },
      error_file: './logs/backend-3003-error.log',
      out_file: './logs/backend-3003-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: false,
      autorestart: true,
      max_memory_restart: '512M',
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
    // Backend Instance 4
    {
      name: 'backend-3004',
      script: './backend/dist/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
        INSTANCE_ID: 'backend-4',
      },
      error_file: './logs/backend-3004-error.log',
      out_file: './logs/backend-3004-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: false,
      autorestart: true,
      max_memory_restart: '512M',
      kill_timeout: 5000,
      wait_ready: true,
      listen_timeout: 10000,
    },
  ],
};

